### ISSUE TITLE
VFB Region Rendering Not Working

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#61] opened 2016-04-20 09:45 UTC
If I activate the region render button, it still renders the whole frame.

**Comment by bdancer** [comment] 2017-10-20 15:19
Duplicate of https://github.com/ChaosGroup/vray-for-houdini/issues/185.
Fixed with https://github.com/ChaosGroup/vray-for-houdini/commit/81cc494e9e7b146b93dbe18189486a66efeb63ac.

**Closed by bdancer** 2017-10-20 15:19 UTC
Labels: AppSDK Related, wontfix
