### ISSUE TITLE
No V-Ray Material Subnets?

### ISSUE THREAD

**Issue by galagast** [ChaosGroup/vray-for-houdini#40] opened 2016-03-14 23:26 UTC
In a V-Ray Material SHOP network, it doesn't seem to allow creating subnets out of the nodes.
![subnet_button](https://cloud.githubusercontent.com/assets/16534677/13763048/425db578-ea7e-11e5-8867-1b5be0798a6b.jpg)
![no_subnets](https://cloud.githubusercontent.com/assets/16534677/13763049/4408f95a-ea7e-11e5-9749-b8291a0443cd.JPG)

**Comment by bdancer** [comment] 2018-05-29 14:21
Closing as duplicate of #57.

**Closed by bdancer** 2018-05-29 14:21 UTC
Labels: bug
